### ISSUE TITLE
MacOS Sonoma displaying more than one icon

### ISSUE THREAD

**Issue by tane123** [amrbashir/system_tray#90]
Using MacOS Sonoma (14.0) the icon will display twice on a single monitor. Once the actual tray icon is clicked and/or the current application loses focus it disappears. 

![image](https://github.com/tauri-apps/tray-icon/assets/19453292/ccd7c63d-f278-45e3-937d-ac8497d49fcc)

**Comment by LeeeSe** [comment]
like [this](https://github.com/LeeeSe/MessAuto/issues/26)

**Comment by FabianLars** [comment]
So, i just upgrade from 13.x to 14.1 and i don't see this issue when running the examples. What are you using to test this? Can you share a minimal reproduction? Or was this just fixed in 14.1?

Edit: I also tried your MessAuto app and couldn't see it.

**Comment by rikschennink** [comment]
A customer of mine has reported this one, it showed up in 14.0, they upgraded to 14.1.1 and it's still showing.

I'm on 14.0 and I can't reproduce it.

**Comment by tane123** [comment]
Apologies for the late reply. I recently updated to 14.2.1 and can still reproduce the issue. I am running an M2 Pro mac mini (Mac14,12). Running the tao and winit examples causes the issue but egui example does not. 

I created this [repo](https://github.com/tane123/tray-icon-example) with reproducible examples and screenshots.
When another application is fullscreen, either in focus or off to the side, that is when the bug crops up.

There is a **hacky** fix I have included for the tao example [here](https://github.com/tane123/tray-icon-example/blob/05883c15e88a2a1eca34a6789eda29c993581c12/examples/hack_fix.rs#L46).

I had a troll through your repo and couldn't spot anything obvious.. If you need anymore testing etc or can point me in the right direction so I can make a PR, let me know.

**Comment by davidchalifoux** [comment]
I'm also experiencing this on 14.4.

Edit: It only happens for me when I have an application in fullscreen on my second monitor.

**Comment by rikschennink** [comment]
I upgrade to 14.3.1 hoping to be able to reproduce this but unfortunately still can't.

**Comment by davidchalifoux** [comment]
> I upgrade to 14.3.1 hoping to be able to reproduce this but unfortunately still can't.

Do you happen to have a second monitor?

**Comment by rikschennink** [comment]
> > I upgrade to 14.3.1 hoping to be able to reproduce this but unfortunately still can't.
> 
> Do you happen to have a second monitor?

I have.

**Comment by davidchalifoux** [comment]
> > > I upgrade to 14.3.1 hoping to be able to reproduce this but unfortunately still can't.
> > 
> > 
> > Do you happen to have a second monitor?
> 
> I have.

I figured out that it specifically happens when you have a full-screen application open _before_ you start the Tauri app.
So, steps to reproduce:
- Make an application full-screen
- Start your Tauri app

It happens for me even without a second monitor. Funnily enough, it doesn't happen if you make an application full-screen _after_ starting the Tauri app.

Does this reproduce the problem for you?

**Comment by rikschennink** [comment]
> > > > I upgrade to 14.3.1 hoping to be able to reproduce this but unfortunately still can't.
> > > 
> > > 
> > > Do you happen to have a second monitor?
> > 
> > 
> > I have.
> 
> I figured out that it specifically happens when you have a full-screen application open _before_ you start the Tauri app. So, steps to reproduce:
> 
> * Make an application full-screen
> * Start your Tauri app
> 
> It happens for me even without a second monitor. Funnily enough, it doesn't happen if you make an application full-screen _after_ starting the Tauri app.
> 
> Does this reproduce the problem for you?

Tried to reproduce without secondary monitor attached, no success unfortunately.
